// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: key_protection_service/proto/api.proto

package kpspb

import (
	proto "github.com/GoogleCloudPlatform/key-protection-module/km_common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateKEMKeypairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algo          *proto.HpkeAlgorithm   `protobuf:"bytes,1,opt,name=algo,proto3" json:"algo,omitempty"`
	BindingPubKey []byte                 `protobuf:"bytes,2,opt,name=binding_pub_key,json=bindingPubKey,proto3" json:"binding_pub_key,omitempty"`
	LifespanSecs  uint64                 `protobuf:"varint,3,opt,name=lifespan_secs,json=lifespanSecs,proto3" json:"lifespan_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKEMKeypairRequest) Reset() {
	*x = GenerateKEMKeypairRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKEMKeypairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEMKeypairRequest) ProtoMessage() {}

func (x *GenerateKEMKeypairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEMKeypairRequest.ProtoReflect.Descriptor instead.
func (*GenerateKEMKeypairRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKEMKeypairRequest) GetAlgo() *proto.HpkeAlgorithm {
	if x != nil {
		return x.Algo
	}
	return nil
}

func (x *GenerateKEMKeypairRequest) GetBindingPubKey() []byte {
	if x != nil {
		return x.BindingPubKey
	}
	return nil
}

func (x *GenerateKEMKeypairRequest) GetLifespanSecs() uint64 {
	if x != nil {
		return x.LifespanSecs
	}
	return 0
}

type GenerateKEMKeypairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KemUuid       string                 `protobuf:"bytes,1,opt,name=kem_uuid,json=kemUuid,proto3" json:"kem_uuid,omitempty"`
	KemPubKey     []byte                 `protobuf:"bytes,2,opt,name=kem_pub_key,json=kemPubKey,proto3" json:"kem_pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKEMKeypairResponse) Reset() {
	*x = GenerateKEMKeypairResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKEMKeypairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEMKeypairResponse) ProtoMessage() {}

func (x *GenerateKEMKeypairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEMKeypairResponse.ProtoReflect.Descriptor instead.
func (*GenerateKEMKeypairResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKEMKeypairResponse) GetKemUuid() string {
	if x != nil {
		return x.KemUuid
	}
	return ""
}

func (x *GenerateKEMKeypairResponse) GetKemPubKey() []byte {
	if x != nil {
		return x.KemPubKey
	}
	return nil
}

type DecapAndSealRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KemUuid         string                 `protobuf:"bytes,1,opt,name=kem_uuid,json=kemUuid,proto3" json:"kem_uuid,omitempty"`
	EncapsulatedKey []byte                 `protobuf:"bytes,2,opt,name=encapsulated_key,json=encapsulatedKey,proto3" json:"encapsulated_key,omitempty"`
	Aad             []byte                 `protobuf:"bytes,3,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DecapAndSealRequest) Reset() {
	*x = DecapAndSealRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapAndSealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapAndSealRequest) ProtoMessage() {}

func (x *DecapAndSealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapAndSealRequest.ProtoReflect.Descriptor instead.
func (*DecapAndSealRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *DecapAndSealRequest) GetKemUuid() string {
	if x != nil {
		return x.KemUuid
	}
	return ""
}

func (x *DecapAndSealRequest) GetEncapsulatedKey() []byte {
	if x != nil {
		return x.EncapsulatedKey
	}
	return nil
}

func (x *DecapAndSealRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

type DecapAndSealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SealEnc       []byte                 `protobuf:"bytes,1,opt,name=seal_enc,json=sealEnc,proto3" json:"seal_enc,omitempty"`
	SealedCt      []byte                 `protobuf:"bytes,2,opt,name=sealed_ct,json=sealedCt,proto3" json:"sealed_ct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecapAndSealResponse) Reset() {
	*x = DecapAndSealResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapAndSealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapAndSealResponse) ProtoMessage() {}

func (x *DecapAndSealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapAndSealResponse.ProtoReflect.Descriptor instead.
func (*DecapAndSealResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *DecapAndSealResponse) GetSealEnc() []byte {
	if x != nil {
		return x.SealEnc
	}
	return nil
}

func (x *DecapAndSealResponse) GetSealedCt() []byte {
	if x != nil {
		return x.SealedCt
	}
	return nil
}

type EnumerateKEMKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateKEMKeysRequest) Reset() {
	*x = EnumerateKEMKeysRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateKEMKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateKEMKeysRequest) ProtoMessage() {}

func (x *EnumerateKEMKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateKEMKeysRequest.ProtoReflect.Descriptor instead.
func (*EnumerateKEMKeysRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *EnumerateKEMKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EnumerateKEMKeysRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type KEMKeyInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Algorithm             *proto.HpkeAlgorithm   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KemPubKey             []byte                 `protobuf:"bytes,3,opt,name=kem_pub_key,json=kemPubKey,proto3" json:"kem_pub_key,omitempty"`
	RemainingLifespanSecs uint64                 `protobuf:"varint,4,opt,name=remaining_lifespan_secs,json=remainingLifespanSecs,proto3" json:"remaining_lifespan_secs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *KEMKeyInfo) Reset() {
	*x = KEMKeyInfo{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KEMKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KEMKeyInfo) ProtoMessage() {}

func (x *KEMKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KEMKeyInfo.ProtoReflect.Descriptor instead.
func (*KEMKeyInfo) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *KEMKeyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KEMKeyInfo) GetAlgorithm() *proto.HpkeAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *KEMKeyInfo) GetKemPubKey() []byte {
	if x != nil {
		return x.KemPubKey
	}
	return nil
}

func (x *KEMKeyInfo) GetRemainingLifespanSecs() uint64 {
	if x != nil {
		return x.RemainingLifespanSecs
	}
	return 0
}

type EnumerateKEMKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KEMKeyInfo          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateKEMKeysResponse) Reset() {
	*x = EnumerateKEMKeysResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateKEMKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateKEMKeysResponse) ProtoMessage() {}

func (x *EnumerateKEMKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateKEMKeysResponse.ProtoReflect.Descriptor instead.
func (*EnumerateKEMKeysResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *EnumerateKEMKeysResponse) GetKeys() []*KEMKeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *EnumerateKEMKeysResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type DestroyKEMKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KemUuid       string                 `protobuf:"bytes,1,opt,name=kem_uuid,json=kemUuid,proto3" json:"kem_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKEMKeyRequest) Reset() {
	*x = DestroyKEMKeyRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKEMKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEMKeyRequest) ProtoMessage() {}

func (x *DestroyKEMKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEMKeyRequest.ProtoReflect.Descriptor instead.
func (*DestroyKEMKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyKEMKeyRequest) GetKemUuid() string {
	if x != nil {
		return x.KemUuid
	}
	return ""
}

type DestroyKEMKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKEMKeyResponse) Reset() {
	*x = DestroyKEMKeyResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKEMKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEMKeyResponse) ProtoMessage() {}

func (x *DestroyKEMKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEMKeyResponse.ProtoReflect.Descriptor instead.
func (*DestroyKEMKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{8}
}

type GetKEMKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KemUuid       string                 `protobuf:"bytes,1,opt,name=kem_uuid,json=kemUuid,proto3" json:"kem_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKEMKeyRequest) Reset() {
	*x = GetKEMKeyRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKEMKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKEMKeyRequest) ProtoMessage() {}

func (x *GetKEMKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKEMKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKEMKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetKEMKeyRequest) GetKemUuid() string {
	if x != nil {
		return x.KemUuid
	}
	return ""
}

type GetKEMKeyResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	KemPubKey             []byte                 `protobuf:"bytes,1,opt,name=kem_pub_key,json=kemPubKey,proto3" json:"kem_pub_key,omitempty"`
	BindingPubKey         []byte                 `protobuf:"bytes,2,opt,name=binding_pub_key,json=bindingPubKey,proto3" json:"binding_pub_key,omitempty"`
	Algorithm             *proto.HpkeAlgorithm   `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	RemainingLifespanSecs uint64                 `protobuf:"varint,4,opt,name=remaining_lifespan_secs,json=remainingLifespanSecs,proto3" json:"remaining_lifespan_secs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetKEMKeyResponse) Reset() {
	*x = GetKEMKeyResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKEMKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKEMKeyResponse) ProtoMessage() {}

func (x *GetKEMKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKEMKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKEMKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetKEMKeyResponse) GetKemPubKey() []byte {
	if x != nil {
		return x.KemPubKey
	}
	return nil
}

func (x *GetKEMKeyResponse) GetBindingPubKey() []byte {
	if x != nil {
		return x.BindingPubKey
	}
	return nil
}

func (x *GetKEMKeyResponse) GetAlgorithm() *proto.HpkeAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *GetKEMKeyResponse) GetRemainingLifespanSecs() uint64 {
	if x != nil {
		return x.RemainingLifespanSecs
	}
	return 0
}

var File_key_protection_service_proto_api_proto protoreflect.FileDescriptor

const file_key_protection_service_proto_api_proto_rawDesc = "" +
	"\n" +
	"&key_protection_service/proto/api.proto\x12!keymanager.key_protection_service\x1a km_common/proto/algorithms.proto\"\x97\x01\n" +
	"\x19GenerateKEMKeypairRequest\x12-\n" +
	"\x04algo\x18\x01 \x01(\v2\x19.keymanager.HpkeAlgorithmR\x04algo\x12&\n" +
	"\x0fbinding_pub_key\x18\x02 \x01(\fR\rbindingPubKey\x12#\n" +
	"\rlifespan_secs\x18\x03 \x01(\x04R\flifespanSecs\"W\n" +
	"\x1aGenerateKEMKeypairResponse\x12\x19\n" +
	"\bkem_uuid\x18\x01 \x01(\tR\akemUuid\x12\x1e\n" +
	"\vkem_pub_key\x18\x02 \x01(\fR\tkemPubKey\"m\n" +
	"\x13DecapAndSealRequest\x12\x19\n" +
	"\bkem_uuid\x18\x01 \x01(\tR\akemUuid\x12)\n" +
	"\x10encapsulated_key\x18\x02 \x01(\fR\x0fencapsulatedKey\x12\x10\n" +
	"\x03aad\x18\x03 \x01(\fR\x03aad\"N\n" +
	"\x14DecapAndSealResponse\x12\x19\n" +
	"\bseal_enc\x18\x01 \x01(\fR\asealEnc\x12\x1b\n" +
	"\tsealed_ct\x18\x02 \x01(\fR\bsealedCt\"G\n" +
	"\x17EnumerateKEMKeysRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xad\x01\n" +
	"\n" +
	"KEMKeyInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\talgorithm\x18\x02 \x01(\v2\x19.keymanager.HpkeAlgorithmR\talgorithm\x12\x1e\n" +
	"\vkem_pub_key\x18\x03 \x01(\fR\tkemPubKey\x126\n" +
	"\x17remaining_lifespan_secs\x18\x04 \x01(\x04R\x15remainingLifespanSecs\"x\n" +
	"\x18EnumerateKEMKeysResponse\x12A\n" +
	"\x04keys\x18\x01 \x03(\v2-.keymanager.key_protection_service.KEMKeyInfoR\x04keys\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"1\n" +
	"\x14DestroyKEMKeyRequest\x12\x19\n" +
	"\bkem_uuid\x18\x01 \x01(\tR\akemUuid\"\x17\n" +
	"\x15DestroyKEMKeyResponse\"-\n" +
	"\x10GetKEMKeyRequest\x12\x19\n" +
	"\bkem_uuid\x18\x01 \x01(\tR\akemUuid\"\xcc\x01\n" +
	"\x11GetKEMKeyResponse\x12\x1e\n" +
	"\vkem_pub_key\x18\x01 \x01(\fR\tkemPubKey\x12&\n" +
	"\x0fbinding_pub_key\x18\x02 \x01(\fR\rbindingPubKey\x127\n" +
	"\talgorithm\x18\x03 \x01(\v2\x19.keymanager.HpkeAlgorithmR\talgorithm\x126\n" +
	"\x17remaining_lifespan_secs\x18\x04 \x01(\x04R\x15remainingLifespanSecs2\xb6\x05\n" +
	"\x14KeyProtectionService\x12\x91\x01\n" +
	"\x12GenerateKEMKeypair\x12<.keymanager.key_protection_service.GenerateKEMKeypairRequest\x1a=.keymanager.key_protection_service.GenerateKEMKeypairResponse\x12\x7f\n" +
	"\fDecapAndSeal\x126.keymanager.key_protection_service.DecapAndSealRequest\x1a7.keymanager.key_protection_service.DecapAndSealResponse\x12\x8b\x01\n" +
	"\x10EnumerateKEMKeys\x12:.keymanager.key_protection_service.EnumerateKEMKeysRequest\x1a;.keymanager.key_protection_service.EnumerateKEMKeysResponse\x12\x82\x01\n" +
	"\rDestroyKEMKey\x127.keymanager.key_protection_service.DestroyKEMKeyRequest\x1a8.keymanager.key_protection_service.DestroyKEMKeyResponse\x12v\n" +
	"\tGetKEMKey\x123.keymanager.key_protection_service.GetKEMKeyRequest\x1a4.keymanager.key_protection_service.GetKEMKeyResponseBYZWgithub.com/GoogleCloudPlatform/key-protection-module/key_protection_service/proto;kpspbb\x06proto3"

var (
	file_key_protection_service_proto_api_proto_rawDescOnce sync.Once
	file_key_protection_service_proto_api_proto_rawDescData []byte
)

func file_key_protection_service_proto_api_proto_rawDescGZIP() []byte {
	file_key_protection_service_proto_api_proto_rawDescOnce.Do(func() {
		file_key_protection_service_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_protection_service_proto_api_proto_rawDesc), len(file_key_protection_service_proto_api_proto_rawDesc)))
	})
	return file_key_protection_service_proto_api_proto_rawDescData
}

var file_key_protection_service_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_key_protection_service_proto_api_proto_goTypes = []any{
	(*GenerateKEMKeypairRequest)(nil),  // 0: keymanager.key_protection_service.GenerateKEMKeypairRequest
	(*GenerateKEMKeypairResponse)(nil), // 1: keymanager.key_protection_service.GenerateKEMKeypairResponse
	(*DecapAndSealRequest)(nil),        // 2: keymanager.key_protection_service.DecapAndSealRequest
	(*DecapAndSealResponse)(nil),       // 3: keymanager.key_protection_service.DecapAndSealResponse
	(*EnumerateKEMKeysRequest)(nil),    // 4: keymanager.key_protection_service.EnumerateKEMKeysRequest
	(*KEMKeyInfo)(nil),                 // 5: keymanager.key_protection_service.KEMKeyInfo
	(*EnumerateKEMKeysResponse)(nil),   // 6: keymanager.key_protection_service.EnumerateKEMKeysResponse
	(*DestroyKEMKeyRequest)(nil),       // 7: keymanager.key_protection_service.DestroyKEMKeyRequest
	(*DestroyKEMKeyResponse)(nil),      // 8: keymanager.key_protection_service.DestroyKEMKeyResponse
	(*GetKEMKeyRequest)(nil),           // 9: keymanager.key_protection_service.GetKEMKeyRequest
	(*GetKEMKeyResponse)(nil),          // 10: keymanager.key_protection_service.GetKEMKeyResponse
	(*proto.HpkeAlgorithm)(nil),        // 11: keymanager.HpkeAlgorithm
}
var file_key_protection_service_proto_api_proto_depIdxs = []int32{
	11, // 0: keymanager.key_protection_service.GenerateKEMKeypairRequest.algo:type_name -> keymanager.HpkeAlgorithm
	11, // 1: keymanager.key_protection_service.KEMKeyInfo.algorithm:type_name -> keymanager.HpkeAlgorithm
	5,  // 2: keymanager.key_protection_service.EnumerateKEMKeysResponse.keys:type_name -> keymanager.key_protection_service.KEMKeyInfo
	11, // 3: keymanager.key_protection_service.GetKEMKeyResponse.algorithm:type_name -> keymanager.HpkeAlgorithm
	0,  // 4: keymanager.key_protection_service.KeyProtectionService.GenerateKEMKeypair:input_type -> keymanager.key_protection_service.GenerateKEMKeypairRequest
	2,  // 5: keymanager.key_protection_service.KeyProtectionService.DecapAndSeal:input_type -> keymanager.key_protection_service.DecapAndSealRequest
	4,  // 6: keymanager.key_protection_service.KeyProtectionService.EnumerateKEMKeys:input_type -> keymanager.key_protection_service.EnumerateKEMKeysRequest
	7,  // 7: keymanager.key_protection_service.KeyProtectionService.DestroyKEMKey:input_type -> keymanager.key_protection_service.DestroyKEMKeyRequest
	9,  // 8: keymanager.key_protection_service.KeyProtectionService.GetKEMKey:input_type -> keymanager.key_protection_service.GetKEMKeyRequest
	1,  // 9: keymanager.key_protection_service.KeyProtectionService.GenerateKEMKeypair:output_type -> keymanager.key_protection_service.GenerateKEMKeypairResponse
	3,  // 10: keymanager.key_protection_service.KeyProtectionService.DecapAndSeal:output_type -> keymanager.key_protection_service.DecapAndSealResponse
	6,  // 11: keymanager.key_protection_service.KeyProtectionService.EnumerateKEMKeys:output_type -> keymanager.key_protection_service.EnumerateKEMKeysResponse
	8,  // 12: keymanager.key_protection_service.KeyProtectionService.DestroyKEMKey:output_type -> keymanager.key_protection_service.DestroyKEMKeyResponse
	10, // 13: keymanager.key_protection_service.KeyProtectionService.GetKEMKey:output_type -> keymanager.key_protection_service.GetKEMKeyResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_key_protection_service_proto_api_proto_init() }
func file_key_protection_service_proto_api_proto_init() {
	if File_key_protection_service_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_protection_service_proto_api_proto_rawDesc), len(file_key_protection_service_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_protection_service_proto_api_proto_goTypes,
		DependencyIndexes: file_key_protection_service_proto_api_proto_depIdxs,
		MessageInfos:      file_key_protection_service_proto_api_proto_msgTypes,
	}.Build()
	File_key_protection_service_proto_api_proto = out.File
	file_key_protection_service_proto_api_proto_goTypes = nil
	file_key_protection_service_proto_api_proto_depIdxs = nil
}
