package workloadservice

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/uuid"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	kpscc "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service/key_custody_core"
	keymanager "github.com/GoogleCloudPlatform/key-protection-module/km_common/proto"

	kps "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service"
	kpspb "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service/proto"
)

// TestIntegrationGRPC_EndToEnd spins up a live KPS gRPC server and a WSD server,
// and verifies communication between them.
func TestIntegrationGRPC_EndToEnd(t *testing.T) {
	// 1. Start a TCP listener on a free port
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to listen on tcp: %v", err)
	}

	// 2. Instantiate key_protection_service.NewService()
	kpsSvc := kps.NewService()

	// 3. Instantiate key_protection_service.NewGrpcServer()
	kpsGrpcServer := kps.NewGrpcServer(kpsSvc)

	// 4. Register the server and serve in a background goroutine
	grpcServer := grpc.NewServer()
	kpspb.RegisterKeyProtectionServiceServer(grpcServer, kpsGrpcServer)
	go func() {
		if err := grpcServer.Serve(listener); err != nil {
			// Serve always returns an error when Stop is called, ignore
		}
	}()
	defer grpcServer.Stop()

	// 5. Create a gRPC client connection to that listener
	conn, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatalf("failed to dial grpc server: %v", err)
	}
	defer conn.Close()

	// 6. Instantiate the remoteKeyProtectionService with that client
	kpsClient := kpspb.NewKeyProtectionServiceClient(conn)
	remoteKps := NewRemoteKeyProtectionService(kpsClient)

	// 7. Start the WSD HTTP server (using the remoteKeyProtectionService)
	// We use a mock WorkloadService since this test focuses on KPS integration.
	mockWsd := &mockWorkloadService{uuid: uuid.New(), pubKey: []byte("thirty-two-bytes-of-dummy-pubkey")}
	wsdServer, err := NewServer(remoteKps, mockWsd, filepath.Join(t.TempDir(), "test.sock"))
	if err != nil {
		t.Fatalf("failed to create wsd server: %v", err)
	}
	defer func() {
		wsdServer.listener.Close()
		close(wsdServer.claimsChan)
	}()

	ts := httptest.NewServer(wsdServer.Handler())
	defer ts.Close()

	client := ts.Client()

	// --- 8. Make HTTP requests to exercise the full flow ---

	// A. Generate Key
	genReqBody := []byte(`{"algorithm":{"type":"kem","params":{"kemId":"KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256"}},"lifespan":3600}`)
	genResp, err := client.Post(ts.URL+"/v1/keys:generate_key", "application/json", bytes.NewReader(genReqBody))
	if err != nil {
		t.Fatalf("Generate Key request failed: %v", err)
	}
	if genResp.StatusCode != http.StatusOK {
		t.Fatalf("Generate Key expected status 200, got %d: body %v", genResp.StatusCode, string(func() []byte { b, _ := io.ReadAll(genResp.Body); return b }()))
	}
	var genResMap map[string]interface{}
	if err := json.NewDecoder(genResp.Body).Decode(&genResMap); err != nil {
		t.Fatalf("Failed to decode Generate Key response: %v", err)
	}
	genResp.Body.Close()

	keyHandleObj, ok := genResMap["key_handle"].(map[string]interface{})
	if !ok {
		t.Fatalf("Response missing key_handle map")
	}
	kemUUIDStr, ok := keyHandleObj["handle"].(string)
	if !ok || kemUUIDStr == "" {
		t.Fatalf("Response missing handle string")
	}

	// B. Enumerate Keys
	enumResp, err := client.Get(ts.URL + "/v1/keys")
	if err != nil {
		t.Fatalf("Enumerate Keys request failed: %v", err)
	}
	if enumResp.StatusCode != http.StatusOK {
		t.Fatalf("Enumerate Keys expected status 200, got %d", enumResp.StatusCode)
	}
	var enumResMap map[string]interface{}
	if err := json.NewDecoder(enumResp.Body).Decode(&enumResMap); err != nil {
		t.Fatalf("Failed to decode Enumerate Keys response: %v", err)
	}
	enumResp.Body.Close()

	// Ensure the generated key is in the list
	keysList, ok := enumResMap["key_infos"].([]interface{})
	if !ok {
		t.Fatalf("Enumerate Keys response missing keys array: %v", enumResMap)
	}
	found := false
	for _, keyItem := range keysList {
		keyObj, ok := keyItem.(map[string]interface{})
		if !ok {
			continue
		}
		khObj, ok := keyObj["key_handle"].(map[string]interface{})
		if !ok {
			continue
		}
		if khObj["handle"] == kemUUIDStr {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("Generated key %s not found in Enumerate Keys response", kemUUIDStr)
	}

	// C. Decaps
	// Since we don't have a valid ciphertext generated by Tink/BoringCrypto,
	// DecapAndSeal will fail in KPS Core (FFI), returning an error. WSD should surface this as 500.
	decapReqBody := []byte(`{
		"key_handle": {"handle": "` + kemUUIDStr + `"},
		"ciphertext": {
			"algorithm": "KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256",
			"ciphertext": "invalid-ciphertext-data-that-is-long-enough-to-pass-basic-checks"
		}
	}`)
	decapResp, err := client.Post(ts.URL+"/v1/keys:decap", "application/json", bytes.NewReader(decapReqBody))
	if err != nil {
		t.Fatalf("Decap request failed: %v", err)
	}
	decapResp.Body.Close()

	// Expect 500 because the ciphertext is invalid
	if decapResp.StatusCode != http.StatusInternalServerError {
		t.Fatalf("Decap expected status 500, got %d", decapResp.StatusCode)
	}

	// D. Destroy Key
	destroyReqBody := []byte(`{"key_handle": {"handle": "` + kemUUIDStr + `"}}`)
	destroyResp, err := client.Post(ts.URL+"/v1/keys:destroy", "application/json", bytes.NewReader(destroyReqBody))
	if err != nil {
		t.Fatalf("Destroy request failed: %v", err)
	}
	destroyResp.Body.Close()
	if destroyResp.StatusCode != http.StatusNoContent {
		t.Fatalf("Destroy expected status 204, got %d", destroyResp.StatusCode)
	}
}

// stubKPS lets a test inject error returns into the gRPC server.
type stubKPS struct {
	destroyErr error
}

func (s *stubKPS) GenerateKEMKeypair(_ context.Context, _ *keymanager.HpkeAlgorithm, _ []byte, _ uint64) (uuid.UUID, []byte, error) {
	return uuid.New(), make([]byte, 32), nil
}
func (s *stubKPS) DecapAndSeal(_ context.Context, _ uuid.UUID, _, _ []byte) ([]byte, []byte, error) {
	return nil, nil, nil
}
func (s *stubKPS) EnumerateKEMKeys(_ context.Context, _, _ int) ([]kpscc.KEMKeyInfo, bool, error) {
	return nil, false, nil
}
func (s *stubKPS) DestroyKEMKey(_ context.Context, _ uuid.UUID) error {
	return s.destroyErr
}
func (s *stubKPS) GetKEMKey(_ context.Context, _ uuid.UUID) ([]byte, []byte, *keymanager.HpkeAlgorithm, uint64, error) {
	return nil, nil, nil, 0, nil
}

// TestIntegrationGRPC_ErrorCodeRoundTrip verifies that an FFI status error from
// the KPS backend is mapped to a gRPC code on the wire and back to the matching
// HTTP status by the WSD adapter — i.e. it does NOT collapse to 500.
func TestIntegrationGRPC_ErrorCodeRoundTrip(t *testing.T) {
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to listen on tcp: %v", err)
	}

	stub := &stubKPS{destroyErr: keymanager.Status_STATUS_NOT_FOUND.ToStatus()}
	kpsGrpcServer := kps.NewGrpcServer(stub)

	grpcServer := grpc.NewServer()
	kpspb.RegisterKeyProtectionServiceServer(grpcServer, kpsGrpcServer)
	go func() { _ = grpcServer.Serve(listener) }()
	defer grpcServer.Stop()

	conn, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatalf("failed to dial grpc server: %v", err)
	}
	defer conn.Close()

	remoteKps := NewRemoteKeyProtectionService(kpspb.NewKeyProtectionServiceClient(conn))
	mockWsd := &mockWorkloadService{uuid: uuid.New(), pubKey: []byte("thirty-two-bytes-of-dummy-pubkey")}
	// macOS sockaddr_un caps sun_path at 104 chars; t.TempDir() can exceed that
	// for tests with long names, so use a short hand-rolled tmp path.
	sockDir, err := os.MkdirTemp("", "kps-")
	if err != nil {
		t.Fatalf("mkdir temp: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(sockDir) })
	wsdServer, err := NewServer(remoteKps, mockWsd, filepath.Join(sockDir, "s"))
	if err != nil {
		t.Fatalf("failed to create wsd server: %v", err)
	}
	defer func() {
		wsdServer.listener.Close()
		close(wsdServer.claimsChan)
	}()

	// Pre-populate the WSD's KEM->binding map so handleDestroy reaches KPS instead
	// of short-circuiting on its own "not found" check (which would mask the bug).
	kemUUID := uuid.New()
	wsdServer.mu.Lock()
	wsdServer.kemToBindingMap[kemUUID] = mockWsd.uuid
	wsdServer.mu.Unlock()

	ts := httptest.NewServer(wsdServer.Handler())
	defer ts.Close()

	body := []byte(`{"key_handle": {"handle": "` + kemUUID.String() + `"}}`)
	resp, err := ts.Client().Post(ts.URL+"/v1/keys:destroy", "application/json", bytes.NewReader(body))
	if err != nil {
		t.Fatalf("Destroy request failed: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusNotFound {
		respBody, _ := io.ReadAll(resp.Body)
		t.Fatalf("expected HTTP 404 (round-tripped from FFI NOT_FOUND), got %d: %s", resp.StatusCode, respBody)
	}
}
