package workloadservice

import (
	"bytes"
	"encoding/json"
	"github.com/google/uuid"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"testing"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	kps "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service"
	kpspb "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service/proto"
)

// TestIntegrationGRPC_EndToEnd spins up a live KPS gRPC server and a WSD server,
// and verifies communication between them.
func TestIntegrationGRPC_EndToEnd(t *testing.T) {
	// 1. Start a TCP listener on a free port
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to listen on tcp: %v", err)
	}

	// 2. Instantiate key_protection_service.NewService()
	kpsSvc := kps.NewService()

	// 3. Instantiate key_protection_service.NewGrpcServer()
	kpsGrpcServer := kps.NewGrpcServer(kpsSvc)

	// 4. Register the server and serve in a background goroutine
	grpcServer := grpc.NewServer()
	kpspb.RegisterKeyProtectionServiceServer(grpcServer, kpsGrpcServer)
	go func() {
		if err := grpcServer.Serve(listener); err != nil {
			// Serve always returns an error when Stop is called, ignore
		}
	}()
	defer grpcServer.Stop()

	// 5. Create a gRPC client connection to that listener
	conn, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatalf("failed to dial grpc server: %v", err)
	}
	defer conn.Close()

	// 6. Instantiate the remoteKeyProtectionService with that client
	kpsClient := kpspb.NewKeyProtectionServiceClient(conn)
	remoteKps := NewRemoteKeyProtectionService(kpsClient)

	// 7. Start the WSD HTTP server (using the remoteKeyProtectionService)
	// We use a mock WorkloadService since this test focuses on KPS integration.
	mockWsd := &mockWorkloadService{uuid: uuid.New(), pubKey: []byte("thirty-two-bytes-of-dummy-pubkey")}
	wsdServer, err := NewServer(remoteKps, mockWsd, filepath.Join(t.TempDir(), "test.sock"))
	if err != nil {
		t.Fatalf("failed to create wsd server: %v", err)
	}
	defer func() {
		wsdServer.listener.Close()
		close(wsdServer.claimsChan)
	}()

	ts := httptest.NewServer(wsdServer.Handler())
	defer ts.Close()

	client := ts.Client()

	// --- 8. Make HTTP requests to exercise the full flow ---

	// A. Generate Key
	genReqBody := []byte(`{"algorithm":{"type":"kem","params":{"kemId":"KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256"}},"lifespan":3600}`)
	genResp, err := client.Post(ts.URL+"/v1/keys:generate_key", "application/json", bytes.NewReader(genReqBody))
	if err != nil {
		t.Fatalf("Generate Key request failed: %v", err)
	}
	if genResp.StatusCode != http.StatusOK {
		t.Fatalf("Generate Key expected status 200, got %d: body %v", genResp.StatusCode, string(func() []byte { b, _ := io.ReadAll(genResp.Body); return b }()))
	}
	var genResMap map[string]interface{}
	if err := json.NewDecoder(genResp.Body).Decode(&genResMap); err != nil {
		t.Fatalf("Failed to decode Generate Key response: %v", err)
	}
	genResp.Body.Close()

	keyHandleObj, ok := genResMap["key_handle"].(map[string]interface{})
	if !ok {
		t.Fatalf("Response missing key_handle map")
	}
	kemUUIDStr, ok := keyHandleObj["handle"].(string)
	if !ok || kemUUIDStr == "" {
		t.Fatalf("Response missing handle string")
	}

	// B. Enumerate Keys
	enumResp, err := client.Get(ts.URL + "/v1/keys")
	if err != nil {
		t.Fatalf("Enumerate Keys request failed: %v", err)
	}
	if enumResp.StatusCode != http.StatusOK {
		t.Fatalf("Enumerate Keys expected status 200, got %d", enumResp.StatusCode)
	}
	var enumResMap map[string]interface{}
	if err := json.NewDecoder(enumResp.Body).Decode(&enumResMap); err != nil {
		t.Fatalf("Failed to decode Enumerate Keys response: %v", err)
	}
	enumResp.Body.Close()

	// Ensure the generated key is in the list
	keysList, ok := enumResMap["key_infos"].([]interface{})
	if !ok {
		t.Fatalf("Enumerate Keys response missing keys array: %v", enumResMap)
	}
	found := false
	for _, keyItem := range keysList {
		keyObj, ok := keyItem.(map[string]interface{})
		if !ok {
			continue
		}
		khObj, ok := keyObj["key_handle"].(map[string]interface{})
		if !ok {
			continue
		}
		if khObj["handle"] == kemUUIDStr {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("Generated key %s not found in Enumerate Keys response", kemUUIDStr)
	}

	// C. Decaps
	// Since we don't have a valid ciphertext generated by Tink/BoringCrypto,
	// DecapAndSeal will fail in KPS Core (FFI), returning an error. WSD should surface this as 500.
	decapReqBody := []byte(`{
		"key_handle": {"handle": "` + kemUUIDStr + `"},
		"ciphertext": {
			"algorithm": "KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256",
			"ciphertext": "invalid-ciphertext-data-that-is-long-enough-to-pass-basic-checks"
		}
	}`)
	decapResp, err := client.Post(ts.URL+"/v1/keys:decap", "application/json", bytes.NewReader(decapReqBody))
	if err != nil {
		t.Fatalf("Decap request failed: %v", err)
	}
	decapResp.Body.Close()

	// Expect 500 because the ciphertext is invalid
	if decapResp.StatusCode != http.StatusInternalServerError {
		t.Fatalf("Decap expected status 500, got %d", decapResp.StatusCode)
	}

	// D. Destroy Key
	destroyReqBody := []byte(`{"key_handle": {"handle": "` + kemUUIDStr + `"}}`)
	destroyResp, err := client.Post(ts.URL+"/v1/keys:destroy", "application/json", bytes.NewReader(destroyReqBody))
	if err != nil {
		t.Fatalf("Destroy request failed: %v", err)
	}
	destroyResp.Body.Close()
	if destroyResp.StatusCode != http.StatusNoContent {
		t.Fatalf("Destroy expected status 204, got %d", destroyResp.StatusCode)
	}
}
